### PR TITLE
panc: since debug allows for formatted strings, DebugSuppressed should also allow it

### LINKED ISSUE #178: debug with formatting fails with syntax error
supposed to be added in #122 

following profile
```pan
object template t;

"/a" = {
    debug("hello %s", 'quattor');
    1;
};
```

gives
```
syntax error [/tmp/t.pan:4.5-4.32]
debug() requires exactly one string argument

```

it does work with `error`

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #178

### CODE REVIEW

File: panc/src/main/java/org/quattor/pan/dml/functions/DebugSuppressed.java [hunk 1]
```diff
@@ -30,14 +28,16 @@ Centre National de la Recherche Scientifique (CNRS).
 import org.quattor.pan.template.Context;
 import org.quattor.pan.template.SourceRange;
 
+import static org.quattor.pan.utils.MessageUtils.*;
+
 /**
  * This is a suppressed debug() function call. This will be called when a
  * debug() function call is encountered, but the given debug patter does not
```
Comment (jrha) [inline panc/src/main/java/org/quattor/pan/dml/functions/DebugSuppressed.java]: Could you fix this typo too? I assume it should be:
patter**n**

**Comment by stdweird** [comment]
@jrha done
